python train_softmax.py \
--logs_base_dir logs/facenet_yyx/ \
--models_base_dir models/facenet_yyx/ \
--data_dir /Users/chenyao/Documents/dataset/160/finetune-dataset \
--image_size 160 \
--model_def models.inception_resnet_v1 \
--lfw_dir /Users/chenyao/Documents/dataset/160/LFW_out/ \
--optimizer ADAM \
--learning_rate -1 \
--max_nrof_epochs 20 \
--keep_probability 0.8 \
--random_crop \
--random_flip \
--use_fixed_image_standardization \
--learning_rate_schedule_file ../data/learning_rate_schedule_classifier_casia.txt \
--weight_decay 5e-4 \
--embedding_size 512 \
--lfw_distance_metric 1 \
--lfw_use_flipped_images \
--lfw_subtract_mean \
--validation_set_split_ratio 0.05 \
--validate_every_n_epochs 5 \
--prelogits_norm_loss_factor 5e-4 2>&1 | tee -a logs/facenet_yyx/softmax_sg_20180917_1.log