CUDA_VISIBLE_DEVICES=2,3 python train_multi_gpu_2.py \
--lfw_pairs ../data/pairs.txt \
--lfw_dir /Users/chenyao/Documents/dataset/160/LFW_out \
--lfw_nrof_folds 10 \
--logs_base_dir logs/facenet_yyx/multi_gpu/ \
--models_base_dir models/facenet_yyx/multi_gpu/ \
--data_dir /Users/chenyao/Documents/dataset/160/finetune-dataset \
--image_size 160 \
--model_def models.inception_resnet_v1 \
--optimizer RMSPROP \
--learning_rate -1 \
--weight_decay 1e-4 \
--max_nrof_epochs 20 \
--batch_size 90 \
--epoch_size 1000 \
--people_per_batch 45 \
--images_per_person 40 \
--pretrained_model  \
--learning_rate_schedule_file ../data/learning_rate_schedule.txt \
--keep_probability 0.8 \
--random_crop \
--random_flip \
--embedding_size 128 \
--gpu_memory_fraction 0.9 2>&1 | tee logs/facenet_yyx/multi_gpu/tripletsloss_multi_gpu_20180910_2.log
